// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asjdjamxhbvfkyrawlzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzamRqYW14aGJ2Zmt5cmF3bHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDA3NDgsImV4cCI6MjA2Njk3Njc0OH0.e7CaJgLT7aD3rFx_700_nurPeTHfMLXmmS2AWCle0Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});